services:
    mc:
        image: itzg/minecraft-server
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "25565:25565"
        volumes:
            - ./data:/data
            - ./patches:/patches

        environment:
            # Java Settings
            MEMORY: 16G
            JVM_OPTS: "--add-modules=jdk.incubator.vector"
            #      JVM_XX_OPTS: "-XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -XX:+UseCriticalJavaThreadPriority -XX:+UseFastUnorderedTimeStamps -XX:+UseG1GC -XX:+UseNUMA -XX:+UseVectorCmov -XX:-DontCompileHugeMethods -XX:AllocatePrefetchStyle=3 -XX:G1ConcMarkStepDurationMillis=5 -XX:G1HeapRegionSize=16M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=50 -XX:G1MixedGCCountTarget=3 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=28 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:G1ReservePercent=15 -XX:G1ReservePercent=20 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:InitiatingHeapOccupancyPercent=10 -XX:MaxGCPauseMillis=130 -XX:MaxNodeLimit=240000 -XX:MaxTenuringThreshold=1 -XX:NmethodSweepActivity=1 -XX:NodeLimitFudgeFactor=8000 -XX:NonNMethodCodeHeapSize=12M -XX:NonProfiledCodeHeapSize=194M -XX:ProfiledCodeHeapSize=194M -XX:ReservedCodeCacheSize=400M -XX:SurvivorRatio=32 -XX:ThreadPriorityPolicy=1"
            JVM_XX_OPTS: "-XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+PerfDisableSharedMem -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -XX:+UseCriticalJavaThreadPriority -XX:+UseFastUnorderedTimeStamps -XX:+UseNUMA -XX:+UseVectorCmov -XX:+UseZGC -XX:+ZGenerational -XX:-DontCompileHugeMethods -XX:-ZProactive -XX:AllocatePrefetchStyle=1 -XX:MaxNodeLimit=240000 -XX:NmethodSweepActivity=1 -XX:NodeLimitFudgeFactor=8000 -XX:NonNMethodCodeHeapSize=12M -XX:NonProfiledCodeHeapSize=194M -XX:ProfiledCodeHeapSize=194M -XX:ReservedCodeCacheSize=400M -XX:ThreadPriorityPolicy=1"

            # Server Settings
            #TYPE: FOLIA
            TYPE: PAPER
            VERSION: 1.21.3
            EULA: true
            MOTD: "ยง5chems event"
            ICON: "https://cdn.discordapp.com/icons/1115150825157824523/a_848a00bf7b93e2e29dda9111687cd9da.webp?size=64"
            ENABLE_AUTOPAUSE: true
            USE_SIMD_FLAGS: true

            # Gameplay Settings
            DIFFICULTY: normal
            MAX_PLAYERS: 99
            VIEW_DISTANCE: 16
            SIMULATION_DISTANCE: 8

            DATAPACKS: https://github.com/jadc/raid-server/releases/latest/download/datapack.zip
            REMOVE_OLD_DATAPACKS: true
            RESOURCE_PACK: https://github.com/jadc/raid-server/releases/latest/download/20241201.zip
            RESOURCE_PACK_ENFORCE: true
            VANILLATWEAKS_SHARECODE: QHb4Am

            SEED: "694269427060245297"
            ENABLE_COMMAND_BLOCK: true
            SNOOPER_ENABLED: false
            SPAWN_PROTECTION: 0
            PLAYER_IDLE_TIMEOUT: 15
            MAX_TICK_TIME: -1
            ENFORCE_SECURE_PROFILE: false
            SYNC_CHUNK_WRITES: false
            MAX_CHAINED_NEIGHBOR_UPDATES: 10000
            PATCH_DEFINITIONS: /patches

            OPS: |
                6459bbdf-da1f-441a-92cf-6f1b2fec2e61
                7ce5f13f-faf3-48f9-bba6-669f92598d43

            # Addons
            MODRINTH_PROJECTS: |
                chunky
                freedomchat
                viaversion
            PLUGINS: |
                https://github.com/jadc/ElytraFlight/releases/latest/download/elytraflight.jar
